[workspace]
members = [
  "bin/common",
  "bin/unprll-miner",
  "bin/unprll-wallet-rpc",
  "bin/unprlld",
  "blockchain",
  "blockchain_db",
  "coin_specific",
  "common",
  "core",
  "crypto",
  "p2p",
  "ringct",
  "rpc",
  "transaction_util",
  "varint",
  "wallet"
]
