[workspace]
members = [
  "bin/common",
  "bin/unprll-miner",
  "bin/unprlld",
  "bincode_epee",
  "blockchain",
  "blockchain_db",
  "coin_specific",
  "common",
  "compat",
  "core",
  "crypto",
  "p2p",
  "ringct",
  "rpc",
  "txpool"
]
