[package]
name = "rpc"
version = "0.1.0"
authors = ["Christopher Tobias <ctobias@gmx.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
cryptonote_core = { path = "../core" }
futures = "0.1"
hyper = "0.12"
log = "0.4"
tokio = "0.1"
