[package]
name = "unprll-miner"
version = "0.1.0"
authors = ["Christopher Tobias <ctobias@gmx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bin_common = { path = "../common" }
bincode = "1.1"
coin_specific = { path = "../../coin_specific" }
common = { path = "../../common" }
compat = { path = "../../compat" }
crypto = { path = "../../crypto" }
futures = "0.1"
hex = "0.3"
reqwest = { version = "0.9", features = ["rustls"] }
log = "0.4"
rpc = { path = "../../rpc" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.2"
tokio = "0.1"
