[package]
name = "unprll-miner"
version = "0.1.0"
authors = ["Christopher Tobias <ctobias@gmx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bin_common = { path = "../common" }
bincode = "1.1"
coin_specific = { path = "../../coin_specific" }
common = { path = "../../common" }
crypto = { path = "../../crypto" }
futures = "0.3"
hex = "0.3"
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee", branch = "master" }
log = "0.4"
rpc = { path = "../../rpc" }
serde = { version = "1.0", features = ["derive"] }
structopt = "0.2"
tokio = { version = "0.2", features = ["full"] }
transaction_util = { path = "../../transaction_util" }
wallet = { path = "../../wallet" }
