[package]
name = "unprlld"
version = "1.0.0"
authors = ["Christopher Tobias <ctobias@gmx.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
bin_common = { path = "../common" }
coin_specific = { path = "../../coin_specific" }
common = { path = "../../common" }
cryptonote_core = { path = "../../core" }
futures = "0.3"
log = "0.4"
p2p = { path = "../../p2p" }
rpc = { path = "../../rpc" }
rustyline = "5.0"
structopt = "0.2"
tokio = { version = "0.2", features = ["full"] }
