[package]
name = "cryptonote_core"
version = "1.0.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
log = "0.4"
blockchain_db = { path = "../blockchain_db" }
crypto = { path = "../crypto" }
cryptonote_common = { path = "../common" }
