[package]
name = "blockchain"
version = "1.0.0"
authors = ["Christopher Tobias <ctobias@gmx.com>"]
edition = "2018"

[dependencies]
blockchain_db = { path = "../blockchain_db" }
common = { path = "../common" }
crypto = { path = "../crypto" }
