[package]
name = "cryptonote_common"
version = "1.0.0"
authors = ["Christopher Tobias <ctobias@gmx.com>"]
edition = "2018"

[dependencies]
crypto = { path = "../crypto" }
hex = "0.3"
log = "0.4"
serde_json = "1.0"

[lib]
path = "lib.rs"
