[package]
name = "bin_common"
version = "1.0.0"
authors = ["Christopher Tobias <ctobias@gmx.com>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4"
fern = { version = "0.5", features = ["colored"] }
